### PR TITLE
Fix lineage checks in UI

### LINKED ISSUE #2266: Fix lineage
The current way the frontend handles lineage is incorrect. Fixing lineage will require #2258 because of collector.

How lineage affects connectability is described by this pseudocode:
```js
let sourceL = getLineage(sourceNode);
if (isIterator(targetNode)) {
  // the inputs of iterator nodes only allow non-iterator connections
  return sourceL === undefined ? CONNECTABLE : INVALID;
}
if (isRegularNode(targetNode)) {
  if (sourceL === undefined) return CONNECTABLE;
  let targetL = getLineage(targetNode, excluded=targetInput)
  return targetL === undefined || targetL === sourceL ? CONNECTABLE : INVALID;
}
assert(isCollector(targetNode));
if (isIteratorInput(targetInput)) {
  if (sourceL === undefined) return INVALID;
  let targetL = getLineage(targetNode.iteratorInputs, excluded=targetInput)
  return targetL === undefined || targetL === sourceL ? CONNECTABLE : INVALID;
} else {
  // the non-iterator inputs of collector nodes only allow non-iterator connections
  return sourceL === undefined ? CONNECTABLE : INVALID;
}
```

[Original discussion](https://discord.com/channels/930865462852591648/1078534152464384152/1162842110022668288).

### PR DESCRIPTION
**Pull request by RunDevelopment**
Fixes #2266.

This PR fixes the lineage checks for nodes. They should just work now, even in more difficult cases. I also added lineage checks to `checkNodeValidity` which ensures that a chain with invalid lineage never makes it to the backend. This also means that we now see lineage errors in the footer.

Note: It is still possible to create invalid connections using the context node selector. I haven't touched that part of the code yet. However, invalid connections will be correctly detected as such. I'll fix the context selector in a follow-up PR.

Examples:
image
image
image

### CODE REVIEW

**Comment by joeyballentine** [comment]
Maybe this would be better suited to a follow up PR, but I kinda wonder if we should change the verbiage we use to use a more user-friendly term rather than iterator. From a user perspective, any iterator/iterable is just a sequence, list, batch, etc rather than something that iterates over some data. Perhaps we can explain it that way? I'm not super sure about that though

File: src/common/nodes/checkNodeValidity.ts [hunk 1]
```diff
@@ -118,3 +148,62 @@ export const checkRequiredInputs = (schema: NodeSchema, inputData: InputData): V
...
+    sourceLineage: Lineage | null,
+    nodeId: string,
+    inputId: InputId,
+    schema: NodeSchema,
+    chainLineage: ChainLineage
+): Validity => {
+    const input = schema.inputs.find((i) => i.id === inputId)!;
+
+    const differentLineage = () =>
+        invalid('Cannot connect node to 2 different sequence of different origin.');
```
Comment (joeyballentine) [inline src/common/nodes/checkNodeValidity.ts:162]:
```suggestion
        invalid('Cannot connect node to 2 different sequences of different origin.');
```

File: src/common/nodes/checkNodeValidity.ts [hunk 2]
```diff
@@ -118,3 +148,62 @@ export const checkRequiredInputs = (schema: NodeSchema, inputData: InputData): V
...
+    const nonIteratorInput = () => invalid(`Input ${input.label} cannot be connect to a sequence.`);
```
Comment (joeyballentine) [inline src/common/nodes/checkNodeValidity.ts:163]:
```suggestion
    const nonIteratorInput = () => invalid(`Input ${input.label} cannot be connected to a sequence.`);
```

**Review by joeyballentine — APPROVED** [review]
